# Generated by Django 4.2.13 on 2024-06-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('control_id', models.AutoField(primary_key=True, serialize=False)),
                ('control', models.CharField(help_text='Create a new control e.g superuser, Admin, Auditor, Operator', max_length=20)),
                ('explain_control', models.TextField(help_text='Explain what actions they can perform e.g. Edit, delete, Atp, M/c Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(help_text='Create new department, e.g. ME, Quality', max_length=30)),
                ('plant', models.CharField(help_text='Create new Plant, e.g. 1170, 1130', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text='create new role e.g. Operator, Supervisior, HOD, Manager', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField()),
                ('control', models.ForeignKey(blank=True, db_column='control', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.control')),
                ('department', models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.department')),
                ('role', models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.role')),
            ],
        ),
    ]
