# Generated by Django 4.2.13 on 2024-08-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomList',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('bom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='e.g. 3G11T 36kW 1500RPM RC 24V IRS')),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(help_text='Hint :- mention CRDI, Mechanical, NA, HE', max_length=20)),
                ('series', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngCheckpoint',
            fields=[
                ('checkpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkpoint', models.TextField(help_text='Hint : Describe the checkpoint requirement ')),
                ('type', models.CharField(help_text='Hint : for tick mark, select checkbox, have any option select dropdown & if want to type value select textbox', max_length=20)),
                ('options', models.CharField(blank=True, help_text="Hint : Between each options kept ' /'  ", max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('esn', models.CharField(max_length=50, unique=True)),
                ('bom', models.CharField(max_length=50)),
                ('insp_type', models.BooleanField(blank=True, null=True)),
                ('for_conversion', models.BooleanField(blank=True, null=True)),
                ('cur_loc', models.IntegerField()),
                ('st01_status', models.BooleanField()),
                ('st01_date', models.DateTimeField()),
                ('st02_status', models.BooleanField(blank=True, null=True)),
                ('st02_date', models.DateTimeField(blank=True, null=True)),
                ('st05_status', models.BooleanField(blank=True, null=True)),
                ('st05_date', models.DateTimeField(blank=True, null=True)),
                ('st10_status', models.BooleanField(blank=True, null=True)),
                ('st10_date', models.DateTimeField(blank=True, null=True)),
                ('st12_status', models.BooleanField(blank=True, null=True)),
                ('st12_date', models.DateTimeField(blank=True, null=True)),
                ('st14_status', models.BooleanField(blank=True, null=True)),
                ('st14_date', models.DateTimeField(blank=True, null=True)),
                ('st20_status', models.BooleanField(blank=True, null=True)),
                ('st20_date', models.DateTimeField(blank=True, null=True)),
                ('st22_status', models.BooleanField(blank=True, null=True)),
                ('st22_date', models.DateTimeField(blank=True, null=True)),
                ('st24_status', models.BooleanField(blank=True, null=True)),
                ('st24_date', models.DateTimeField(blank=True, null=True)),
                ('st30_status', models.BooleanField(blank=True, null=True)),
                ('st30_date', models.DateTimeField(blank=True, null=True)),
                ('st32_status', models.BooleanField(blank=True, null=True)),
                ('st32_date', models.DateTimeField(blank=True, null=True)),
                ('st35_status', models.BooleanField(blank=True, null=True)),
                ('st35_date', models.DateTimeField(blank=True, null=True)),
                ('st40_status', models.BooleanField(blank=True, null=True)),
                ('st40_date', models.DateTimeField(blank=True, null=True)),
                ('st42_status', models.BooleanField(blank=True, null=True)),
                ('st42_date', models.DateTimeField(blank=True, null=True)),
                ('st50_status', models.BooleanField(blank=True, null=True)),
                ('st50_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngModel',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('engmodel', models.CharField(help_text='addition of model & application', max_length=20, unique=True)),
                ('model', models.CharField(help_text='e.g 3G, 4G, 6G, D3V6, D3V8, NEWD', max_length=20)),
                ('application', models.CharField(help_text='e.g Genset, Marine, FMUL, Others', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngResultAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=50, unique=True)),
                ('esn', models.CharField(max_length=25)),
                ('stno', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('emp_id', models.IntegerField()),
                ('username', models.CharField(max_length=25)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngResultHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=100, unique=True)),
                ('esn', models.CharField(max_length=50)),
                ('stno', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('emp_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('bom_srno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engresultheaders', to='ATP.bomlist')),
            ],
        ),
        migrations.CreateModel(
            name='EngResultRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=50, unique=True)),
                ('esn', models.CharField(max_length=25)),
                ('stno', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('emp_id', models.IntegerField()),
                ('username', models.CharField(max_length=25)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc_id', models.IntegerField()),
                ('location_desc', models.CharField(max_length=40)),
                ('activity', models.CharField(max_length=20)),
                ('pass_field', models.IntegerField(db_column='pass')),
                ('fail', models.IntegerField()),
                ('result_field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('stno', models.AutoField(primary_key=True, serialize=False)),
                ('op_name', models.CharField(max_length=20, unique=True)),
                ('op_detail', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetAssemblyOpResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('esn', models.CharField(max_length=50)),
                ('crankcase_no', models.CharField(max_length=50)),
                ('fip_no', models.CharField(max_length=50)),
                ('turbo_no', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('operator_id', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('bom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATP.bomlist')),
            ],
        ),
        migrations.CreateModel(
            name='EngResultImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.TextField(unique=True)),
                ('directory', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.engresultheader', to_field='result_id')),
            ],
        ),
        migrations.CreateModel(
            name='EngResultCheckpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=25, unique=True)),
                ('checkpoint_status', models.CharField(max_length=255)),
                ('seq_no', models.IntegerField(blank=True, null=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.engcheckpoint')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.engresultheader', to_field='result_id')),
            ],
        ),
        migrations.CreateModel(
            name='EngineAsslyOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esn', models.CharField(max_length=255)),
                ('crankcase_no', models.CharField(max_length=255)),
                ('fip_no', models.CharField(max_length=255)),
                ('turbo_no', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_id', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineasslyop', to='ATP.bomlist')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(help_text='Give the no in which it will occured in Checksheet')),
                ('map_status', models.BooleanField(help_text='To keep it in checksheet, check checkbox')),
                ('map_date', models.DateTimeField(help_text='Select date')),
                ('map_by', models.IntegerField(help_text='provide employee Id')),
                ('unmap_date', models.DateTimeField(blank=True, help_text='Select date', null=True)),
                ('unmap_by', models.IntegerField(blank=True, help_text='provide employee Id', null=True)),
                ('checkpoint', models.ForeignKey(help_text='Select the Checkpoint from dropdown', on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.engcheckpoint')),
                ('engmodel', models.ForeignKey(db_column='engmodel', help_text='Select the eng model from dropdown', on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.engmodel', to_field='engmodel')),
                ('stno', models.ForeignKey(db_column='stno', help_text='Select the station number from dropdown', on_delete=django.db.models.deletion.DO_NOTHING, to='ATP.operation')),
            ],
        ),
    ]
